app/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from . import login_manager
from markdown import markdown
import bleach

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(64), unique=True)

    def __repr__(self):
        return '<Role %r>' % self.name

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email=db.Column(db.String(64), unique=True, index=True)
    username=db.Column(db.String(64), unique=True, index=True)
    password_hash= db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    summury = db.Column(db.Text)
    summury_html = db.Column(db.Text)

    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship('Category', backref=db.backref('posts', lazy='dynamic'))

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'code', 'blockquote','em', 'i','strong','li','ol','pre','strong','ul','h1','h2','h3','p']
        target.body_html = bleach.linkify(bleach.clean(markdown(value, extensions=['footnotes'], output_format='html'), tags=allowed_tags, strip=True))

    @staticmethod
    def on_changed_summury(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'code', 'blockquote','em', 'i','strong','li','ol','pre','strong','ul','h1','h2','h3','p']
        target.summury_html = bleach.linkify(bleach.clean(markdown(value, output_format='html'),tags=allowed_tags, strip=True))

db.event.listen(Post.body, 'set', Post.on_changed_body)
db.event.listen(Post.summury, 'set', Post.on_changed_summury)

class Category(db.Model):
    __tablename__="category"
    id = db.Column(db.Integer, primary_key=True)
    tag = db.Column(db.String(64))
    count = db.Column(db.Integer, default=1)
    def __init__(self, tag):
        self.tag = tag

    def __repr__(self):
        return '<Category %r>' % self.tag

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SubmitField
from flask_pagedown.fields import PageDownField



class PostForm(Form):
    title = StringField("TITLE")
    body = PageDownField("BODY")
    summury = PageDownField('SUMMURY')
    category=StringField('CATEGORY')
    submit = SubmitField('SUBMIT')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_login import LoginManager
from flask_pagedown import PageDown



bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
pagedown = PageDown()



def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(Config)
    Config.init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask_login import current_user, login_required
from flask import render_template, session, redirect, url_for, request, flash

from .. import db
from . import main
from .forms import PostForm
from ..models import User, Post, Category



PER_POSTS_PER_PAGE=8



@main.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    pagination = \
        Post.query.order_by(Post.timestamp.desc())\
            .paginate(page, per_page=PER_POSTS_PER_PAGE, error_out=False)
    posts = pagination.items
    categorys = Category.query.order_by(Category.count)[::-1]
    return render_template(
        'index.html', posts=posts, pagination=pagination, categorys=categorys)



@main.route('/write', methods=['GET', 'POST'])
@login_required
def write():
    form = PostForm()
    category = Category.query.filter_by(tag=form.category.data).first()
    if form.validate_on_submit():
        if category:
            category.count += 1
            post =\
                Post(title=form.title.data, body=form.body.data,
                     summury=form.summury.data, category=category)
        else:
            post = \
                Post(title=form.title.data, body=form.body.data,
                     summury=form.summury.data,
                     category=Category(tag=form.category.data))
        db.session.add(post)
        return redirect(url_for('.index'))
    return render_template("write.html",form=form)



@main.route('/eidt/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.summury = form.summury.data
        db.session.add(post)
        flash('The post has been updated')
        return redirect(url_for('.post', id = post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.summury.data = post.summury
    return render_template('edit_post.html', form=form)



@main.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    post = Post.query.get_or_404(id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('.index'))



@main.route('/post/<int:id>', methods=['GET'])
def post(id):
    post=Post.query.get_or_404(id)
    return render_template("post.html",post=post)



@main.route('/category/<tag>', methods=['GET'])
def category(tag):

    category=Category.query.filter_by(tag=tag).first()
    posts=category.posts

    return render_template("category_search.html",posts=posts)



@main.route('/about', methods=['GET'])
def about_website():
    return render_template('about.html')



@main.app_errorhandler(404)
def page_not_found(error):
    return render_template("404.html"), 404

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination pagination-minimal" style="background-color:#B1BAB4" align="center">
    
    <li {% if not pagination.has_prev %} class="disabled previous" {% else %} class="previous" {% endif %} >
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled next" {% else %} class="next" {% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/about.html
{% extends  "base.html" %}

{% block title %}
关于网站
{% endblock %}

{% block body %}

<div class="container">
<div class="row">
	<div class="col-md-12">
		<article class="article the-font">
			<div class="comtainer">
				<div class="row">
					<div class="col-md-3">
						<br>

						<div align="center"><img src="http://7xlen8.com1.z0.glb.clouddn.com/avatar.jpg" style="height:220px;width:220px;border-radius:110px;display:block;text-align:center" align="center"></div>
						<br>
						<p class="lead text-center">ALJUN</p>
						<p class="text-center"><em><span style="color:#ABAAAA">ONE MAN CAN CHANGE THE WORLD!	</span></em></p>
						<br>


						<p class="palette-paragraph"><strong>这个是我的个人网站，如果你喜欢，那就按下下面的"LIKE”按钮，给我动力继续写吧</strong></p>
						<div  style="cursor:pointer" class="btn btn-danger btn-large btn-block btn-like-add">LIKE <span class="glyphicon glyphicon-heart" aria-hidden="True"></span></div>
						<hr>
						<p >已经有了这么多<strong>LIKE</strong>:<a href="#"><span id="liked">{{ liked.like_count }}</span></a></p>
					</div>
					<div class="col-md-9">
						<h3>个人信息：</h3>
						<hr>
						<ul>
							<li>姓名：陈阳洋</li>
							<li>网名：Aljun（或者Salamer）</li>
							<li>年龄：19</li>
							<li>生日：1996/2/19</li>
							<li>居住地：北京</li>
							<li>学历：本科大二应用化学在读</li>
							
						</ul>
						<h3>联系方式：</h3>
						<hr>
						<ul>
							<li>EMAIL:<a href="#">contactsalamer@163.com</a></li>
							<li>WEIBO:<a href="http://weibo.com/2277966967/profile">陈阳洋invictus的微博_微博</a></li>
							<li>QQ:3028156088</li>
						</ul>
						<h3>个人代码库：</h3>
						<hr>
						<ul>
							<li>GITHUB:<a href="https://github.com/salamer">https://github.com/salamer</a></li>
							<li>该网站源代码：<a href="https://github.com/salamer/GAGASALAMER_BLOG">https://github.com/salamer/GAGASALAMER</a></li>
						</ul>
						<h3>已学过的：</h3>
						<hr>
						<ul>
							<li>python(django，flask，tornado之类的框架（该网站就是基于flask编写的），爬虫，科学处理与数据分析</li>
							<li>sql</li>
							<li>c,c++（做项目，码算法，看底层）</li>
							<li>使用ruby的ruby on rails框架</li>
							<li>bootstrap，pure等前端相应式布局</li>
							<li>jquery,angularjs</li>
							<li>nodejs</li>
						</ul>
						<h3>发展方向：</h3>
						<hr>
						<ul>
							<li>算法与数据结构学习（ACM）</li>
							<li>机器学习</li>
							<li>数据挖掘</li>
							<li>计算机图像处理</li>
						</ul>
						<h3>其他兴趣：</h3>
						<hr>
						<ul>
							<li>语言：英语，日语</li>
							<li>历史迷，特别二战史，欧洲史，罗马史，日本战国史</li>
							<li>对社会科学也有些想象</li>
						</ul>
						
						<h3>格言：</h3>
						<hr>
						<blockquote>
							<p></p>
							<p>也许多少年后在某个地方，</p>
							<p>我将轻声叹息将往事回顾：</p>
							<p>一片树林里分出两条路——</p>
							<p>而我选择了人迹更少的一条，</p>
							<p>从此决定了我一生的道路。</p>
							<p class="text-right"><em>——Robert Frost 《The Road Not Taken》</em></p>
						</blockquote>
						<hr>
						<p >我想感谢 <strong>BIG SEAN,KANYE WEST</strong><strong>和 JUSTING BIEBER </strong>，感谢他们的歌曲陪伴了我走过一个个敲键盘的夜晚。</p>
						<img src="http://7xlen8.com1.z0.glb.clouddn.com/kanye3.jpg" >
						<hr>
						<p class="lead">这是我的个人网站，如果你觉得它很有趣，或者内容对你很有帮助，可以qq联系我，请我喝杯茶。</p>
						<hr>
					</div>
					<hr>
					<br>	
					<br>

					</div>
					
				</div>
			
		</article>
			
			
			<article class="article">
						<div class="ds-share flat" data-thread-key="999" data-title="关于GAGASALAMER" data-images="http://7xlen8.com1.z0.glb.clouddn.com/avatar.jpg" data-content="关于GAGASALAMER的网站" data-url="/about">
    <div class="ds-share-inline">
      <ul  class="ds-share-icons-16">
      	
      	<li data-toggle="ds-share-icons-more"><a class="ds-more" href="javascript:void(0);">分享到：</a></li>
        <li><a class="ds-weibo" href="javascript:void(0);" data-service="weibo">微博</a></li>
        <li><a class="ds-qzone" href="javascript:void(0);" data-service="qzone">QQ空间</a></li>
        <li><a class="ds-qqt" href="javascript:void(0);" data-service="qqt">腾讯微博</a></li>
        <li><a class="ds-wechat" href="javascript:void(0);" data-service="wechat">微信</a></li>
      	
      </ul>
      <div class="ds-share-icons-more">
      </div>
    </div>
 </div>
			<!-- 多说评论框 start -->
	<div class="ds-thread" data-thread-key="aboutMe" data-title="MyInfomation" data-url="/about"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"gagablog"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->

		
  	
  	</article>
  	<article>
  		
  	</article>
  	</div>
</div>
</div>




{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %} | MAIN</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='bootstrap/css/bootstrap.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='dist/css/flat-ui.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='mystyle.css') }}">

	<link rel="shortcut icon" href="{{ url_for('static',filename='rambo.ico') }}">

	<script type="text/javascript" src="{{ url_for('static',filename='dist/js/vendor/jquery.min.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static',filename='bootstrap/js/bootstrap.min.js') }}"></script>


	<script type="text/javascript" src="{{ url_for('static',filename='mystyle.js') }}"></script>
<style type="text/css">
	h1{
		font-size:50px;
	}
	h2{
		font-size: 40px;
	}
	h3{
		font-size: 30px;
	}
	p{
		font-size: 15px;
	}
	blockquote p{
		font-size: 17px;
	}
	body{
		font-size: 15px;
	}
</style>
</head>
<script type="text/javascript">
$SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
</script>
<body style="background-color:#EEE">
	<nav class="navbar navbar-default navbar-Amethyst" role="navigation" style="margin:10px 0px;">
	<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="/">MAIN</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-01">

    <ul class="nav navbar-nav">
    	<li>
    	
    </li>
      <li class="active"><a href="/">MYBLOG</a></li>
<!-- 留用      <li><a href="/about">ABOUTME</a></li> -->
	  {% if current_user.is_authenticated  %}
	  <li><a href="{{ url_for('main.write')}}">WRITE</a></li>
      {% endif  %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
	  	  {% if current_user.is_authenticated  %}
		  <li id="signin_icon"><a href="{{ url_for('auth.logout')}}">Sign Out</a></li>
    	  {% else  %}
		  <li id="signin_icon"><a href="{{ url_for('auth.login')}}">Sign In</a></li>
    	  {% endif  %}

        </ul>
{% block page_content  %}
{% endblock  %}


  </div><!-- /.navbar-collapse -->
  </div>
</nav><!-- /navbar -->
{% block body %}
{% endblock %}


<div style="background:#000033 none repeat scroll 0% 0%;color:#BFC9D3">
	<div class="container">
		<div class="row" style="padding-top:30px;">
			<div class="col-md-7">
				<p class="lead"> On the Road <a href="/">--CHENG</a>.</p>
				<p >Talk is <strong>Cheap.</strong>Show me the  <strong>Code</strong>.</p>
				<p >                        -- <strong>Linus.</strong></p>
				
			</div>
			<div class="col-md-5">
				<div>
					<h5 style="margin-bottom:15px;margin-left:18px;"><strong>CONTACT ME</strong></h5>
					<ul>
						<li><a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> &nbsp WECHAT</a></li>
						<li><a href="http://weibo.com"><span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span> &nbsp WEIBO</li>

						
<li><a href="https://github.com/HelloRambo"><span class="glyphicon glyphicon-grain" aria-hidden="true"></span>&nbsp GITHUB</a></li>
						<li><a href="#"><span class=" glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp EMAIL:<strong>chengwenjun1994@msn.cn</strong></a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-12">
				<p> <small>© COPYRIGHT BY WENJUN 2016</small></p>
			</div>
		</div>
	</div>
</div>

</body>
</html>

app/templates/category_search.html
{% extends "base.html" %}

{% block title %}
分类
{% endblock %}

{% block body %}
{% import "_macros.html" as macro %}

	
	<nav class="navbar navbar-default navbar-lg navbar-Amethyst" role="navigation" style="display:none">
	<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="#">GAGASALAMER</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-01">

    <ul class="nav navbar-nav">
    	<li>
    	
    </li>
      <li class="active"><a href="#fakelink">MYBLOG</a></li>
      <li><a href="#fakelink">ABOUTME</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
    	<li id="signup_icon"><a href="#">SIGNUP</a></li>
    	
    	

        </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav><!-- /navbar -->

<div class="jumbotron" style="background-color:#2c3e50">
	<div class="container">
		<h2 style="color:#E7DBDB">我是文俊，希望我的文章能给你帮助!</h2>
<!--		<p class="lead" style="color:#E7DBDB">wanna know more ,please click </p>
            <a href="/about"><button class="btn btn-danger btn-wide">关于我</button></a>  -->
	</div>
</div>

<div class="container">
<div class="row">
        {% if categorys %}
	<div class="col-md-9">
      {% else %}
      <div class="col-md-12">
      {% endif %}
	{% for post in posts %}
		<article class="article the-font">
			<a href="/post/{{ post.id }}"><h2 style="color:#34495E">{{ post.title }}</h2></a>
			<p><small><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span><span style="color:#8C8C8C;">{{ post.timestamp }}</span></small></p>
      <div class="post-alert">本博客采用创作共用版权协议, 要求署名、非商业用途和保持一致. 转载本博客文章必须也遵循署名-非商业用途-保持一致的创作共用协议</div>
			<p>{{ post.summury_html|safe }}</p>
			
			<div style="border-top:1px solid #EBEBEB;padding:10px 5px;margin-top:20px;">
				
        <p><a href="/category/{{ post.category.tag }}"><span class="label label-default text-left"><span class="glyphicon glyphicon-leaf" aria-hidden="true"></span> {{ post.category.tag }}</span>
        <a href="/post/{{ post.id }}" style="float:right"><button class="btn  btn-primary btn-wide text-right"><span class="glyphicon glyphicon-fire
glyphicon " aria-hidden="true"></span>  了解更多</button></a></p>
			</div>
		</article>
	{% endfor %}
	{% if pagination %}
	{{ macro.pagination_widget(pagination,'.index') }}	
      {% endif %}
	</div>
    
</div>
</div>




{% endblock %}

app/templates/edit_post.html
{% extends "base.html" %}
{% block body %}

{{ pagedown.include_pagedown() }}
	




<div class="container">
<div class="row">
	<div class="col-md-12">
		<div style="box-shadow:5px 5px 20px #CCC;background-color:white;padding:20px 30px;margin-bottom:40px;">
		<h2 class="text-center">TO EDIT THE BLOG!</h2>
		{% if messages %}
		{% for message in messages %}
		<p class="alert alert-warning">{{ message }}</p>
		{% endfor %}
		{% endif %}
		{% macro render_field(field) %}
		{% for error in field.errors %}
		{{ error }}
		{% endfor %}
		{% endmacro %}
			<form class="form-horizontal" method="post" action="">
				{{ form.csrf_token }}
				<div class="form-group">
    					<label for="inputEmail3" class="col-sm-1 control-label">{{ form.title.label }}</label>
    						<div class="col-sm-11">
      						{{ form.title(class="form-control",placeholder="the title") }}
   						 </div>
  				</div>
  				<div class="form-group">
    					<label for="inputEmail3" class="col-sm-1 control-label">{{ form.body.label }}</label>
    						<div class="col-sm-11">
      						{{ form.body(class="form-control",placeholder="the body") }}
   						 </div>
  				</div>
  				<div class="form-group">
    					<label for="inputEmail3" class="col-sm-1 control-label">{{ form.summury.label }}</label>
    						<div class="col-sm-11">
      						{{ form.summury(class="form-control",placeholder="the summury") }}
   						 </div>
  				</div>
  				

  				
  				<input type="submit" value="Go" class="btn btn-large btn-block btn-primary">
			</form>
			
		</div>
		
  	</div>
  	
</div>
</div>





{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}
CHENGWENJUN
{% endblock %}

{% block body %}
{% import "_macros.html" as macro %}

	
	<nav class="navbar navbar-default navbar-lg navbar-Amethyst" role="navigation" style="display:none">
	<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="#">MAIN</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-01">

    <ul class="nav navbar-nav">
    	<li>
    	
    </li>
      <li class="active"><a href="#fakelink">MYBLOG</a></li>
	  <!--about me 留用 
      <li><a href="#fakelink">ABOUTME</a></li>
 	  -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
    	<li id="signup_icon"><a href="#">SIGNUP</a></li>
    	
    	

        </ul>

  </div><!-- /.navbar-collapse -->
  </div>
</nav><!-- /navbar -->

<div class="jumbotron" style="background-color:#000033">
	<div class="container">
		<h2 style="color:#E7DBDB">
{% if current_user.is_authenticated  %}
	 Welocome Back, WENJUN
{% else  %}
	 Welocome! Have a good day!
{% endif  %}
		
		</h2>
		<!--about me
		<p class="lead" style="color:#E7DBDB">wanna know more , please click </p>
            <a href="about"><button class="btn btn-danger btn-wide the-font">关于我</button></a>
		 -->
	</div>
</div>

<div class="container">
<div class="row">

	<div class="col-md-9">

	{% for post in posts %}
		<article class="article the-font" style="display:none">


			<a href="/post/{{ post.id }}"><h3 style="color:#34495E">{{ post.title }}</h3></a>
			<p><small><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span><span style="color:#8C8C8C;">{{ post.timestamp }}</span></small></p>
			<div class="post-alert">随意转载，不需署名，就说是你写的。若你愿意署名，我将不胜感激。</div>
			<p>{{ post.summury_html|safe }}</p>
			
			<div style="border-top:1px solid #EBEBEB;padding:10px 5px;margin-top:20px;">
				<p><a href="/category/{{ post.category.tag }}"><span class="label label-default text-left"><span class="glyphicon glyphicon-leaf" aria-hidden="true"></span> {{ post.category.tag }}</span>
				<a href="/post/{{ post.id }}" style="float:right"><button class="btn  btn-primary btn-wide text-right"><span class="glyphicon glyphicon-fire
glyphicon " aria-hidden="true"></span>  了解更多</button></a></p>
			</div>
		</article>
	{% endfor %}
	{% if pagination %}
	{{ macro.pagination_widget(pagination,'.index') }}	
      	{% endif %}
	</div>

	<div class="col-md-3">
	
		<div class="share mrl the-font" style="background-color:#FFF;box-shadow:5px 5px 20px #CCC;width:260px;">
		<div style="padding:10px;">
				<div style="border-bottom:1px solid #DAD4D4;;padding:10px 10px;">
					<h5><span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>CATEGORY</h5>
				</div>

				<ul>
					{% for category in categorys %}
					<li class="presentation" style="padding-top:0px;"><a href="/category/{{ category.tag }}" ><p><span style="font-size:15px;">> {{ category.tag|upper }}</span><span class="badge text-right" style="float:right">{{ category.count }}</span></p></a></li>
					{% endfor %}
				</ul>

		</div>
		</div>
		
<!--		<div class="tile" style="margin-top:40px;box-shadow:5px 5px 20px #CCC;background-color:#FFF">
			<div style="border:5px solid #FFF;border-radius:300px;width:128px;height:128px;margin:0px auto;position:relative;bakeground:#88ACDB none repeat scroll 0% 0%;overflow:hidden">
				<img src="{{ url_for('static',filename='') }}" style="width:100%;height:100%">
			</div>
		</div>
-->	
	</div>

</div>
</div>




{% endblock %}